### ISSUE TITLE
Issue when sourcing the function directly from GitHub.

### ISSUE THREAD

**Issue by GiulianoColosimo** [lvclark/R_genetics_conv#2]
Hello Lindsay,

This function is really great. Thank you for sharing it. I am having some problems making it work.
Two things: the first one is that I have noticed an issue when trying to source it directly from GitHub:

```r
source("https://github.com/lvclark/R_genetics_conv/blob/master/genind2structure.R")

Error in source("https://github.com/lvclark/R_genetics_conv/blob/master/genind2structure.R") : 
  https://github.com/lvclark/R_genetics_conv/blob/master/genind2structure.R:7:1: unexpected '<'
6: 
7: <
   ^
```
The second one is that even if I copy and paste to my computer, it doesn't seem to work with the following message:

```r
>  genind2structure(nancycats, file="nancy_structure.txt", pops=TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘pop’ for signature ‘"genind", "missing"’
Called from: (function (classes, fdef, mtable) 
{
    methods <- .findInheritedMethods(classes, fdef, mtable)
    if (length(methods) == 1L) 
        return(methods[[1L]])
    else if (length(methods) == 0L) {
        cnames <- paste0("\"", vapply(classes, as.character, 
            ""), "\"", collapse = ", ")
        stop(gettextf("unable to find an inherited method for function %s for signature %s", 
            sQuote(fdef@generic), sQuote(cnames)), domain = NA)
    }
    else stop("Internal error in finding inherited methods; didn't return a unique method", 
        domain = NA)
})(list("genind", "missing"), new("standardGeneric", .Data = function (obj, 
    val) 
standardGeneric("pop"), generic = "pop", package = "RCurl", group = list(), 
    valueClass = character(0), signature = c("obj", "val"), default = NULL, 
    skeleton = (function (obj, val) 
    stop("invalid call in method dispatch to 'pop' (no default method)", 
        domain = NA))(obj, val)), <environment>)
Browse[1]>
```
My debugging skills are too primitive but I am trying to give it a go and see what is the problem.
In the meantime if you have a solution that would be awesome.

Thanks

**Comment by GiulianoColosimo** [comment]
Hello again,

I think I found a bug in lines 30 and 31 of your original function:

```r
...
names(popnums) <- as.character(unique(pop(obj)))
popcol <- rep(popnums[as.character(pop(obj))], each=pl)
...
```

I changed these two lines to:

```r
...
names(popnums) <- as.character(unique(obj@pop))
popcol <- rep(popnums[as.character(obj@pop)], each=pl)
...
```
and now it seems to work.
Still don't know what the issue with this source command is.

Cheers

**Comment by lvclark** [comment]
Hi Giuliano,

Your source command should be changed to

```
source("https://raw.githubusercontent.com/lvclark/R_genetics_conv/master/genind2structure.R")
```

(You can find that link by clicking "Raw" when looking at the source code.)  The way you were doing it, it was trying to parse all the HTML and whatever else from the GitHub webpage.

As for the issue with `pop`, did you not have `adegenet` loaded when you ran this function?  Could you test it for me again after running `library(adegenet)`?  If that's the issue I'll modify the function with a `require(adegenet)` statement in there.  For reasons having to do with programming philosophy I prefer to use `pop(obj)` over `obj@pop` if possible.  (Having that level of abstraction from the accessor function means that this `genind2structure` will still work if the underlying data structure of a `genind` object changes.)

Thanks!

**Comment by GiulianoColosimo** [comment]
Hi Lindsay,

I have tried loading again the `adegenet` package but the situation doesn't change. 

```r
> library(adegenet)
> genind2structure(nancycats, file="nancy_structure.txt", pops=TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘pop’ for signature ‘"genind", "missing"’
Called from: (function (classes, fdef, mtable) 
{
    methods <- .findInheritedMethods(classes, fdef, mtable)
    if (length(methods) == 1L) 
        return(methods[[1L]])
    else if (length(methods) == 0L) {
        cnames <- paste0("\"", vapply(classes, as.character, 
            ""), "\"", collapse = ", ")
        stop(gettextf("unable to find an inherited method for function %s for signature %s", 
            sQuote(fdef@generic), sQuote(cnames)), domain = NA)
    }
    else stop("Internal error in finding inherited methods; didn't return a unique method", 
        domain = NA)
})(list("genind", "missing"), new("standardGeneric", .Data = function (obj, 
    val) 
standardGeneric("pop"), generic = "pop", package = "RCurl", group = list(), 
    valueClass = character(0), signature = c("obj", "val"), default = NULL, 
    skeleton = (function (obj, val) 
    stop("invalid call in method dispatch to 'pop' (no default method)", 
        domain = NA))(obj, val)), <environment>)
```

On the flip side, thank you so much for the `source()` solution.

Cheers

**Comment by lvclark** [comment]
I took a closer look at your error output and it seems that both `adegenet` and `RCurl` have a `pop` function and that was causing the issue.  I changed the code to be more specific about using the `adegenet` version.  Let me know if it works.  Thanks!

**Comment by GiulianoColosimo** [comment]
Hi Lindsay, 

It seems like the new code fixed the issue. Now it works like a charm. 

Thanks for your help and for sharing the function.

**Comment by lvclark** [comment]
Super, thanks for letting me know!
